### ISSUE TITLE
qt5 fails to build on archlinux (qt5-5.5.0)

### ISSUE THREAD

**Issue by mmetak** [tsujan/Kvantum#51]
Since the update to qt5-5.5.0, the qt5 style fails to build with this error:
```
  177s] In file included from themeconfig/ThemeConfig.cpp:18:0:
[  177s] themeconfig/ThemeConfig.h:81:5: error: 'QVariant' does not name a type
[  177s]      QVariant getValue(const QString &group, const QString& key, const QString &inherits) const;
[  177s]      ^
[  177s] themeconfig/ThemeConfig.h:86:5: error: 'QVariant' does not name a type
[  177s]      QVariant getValue(const QString &group, const QString& key) const;
[  177s]      ^
[  177s] themeconfig/ThemeConfig.cpp:61:74: error: no 'QVariant Kvantum::ThemeConfig::getValue(const QString&, const QString&) const' member function declared in class 'Kvantum::ThemeConfig'
[  177s]  QVariant ThemeConfig::getValue(const QString& group, const QString& key) const
[  177s]                                                                           ^
[  177s] themeconfig/ThemeConfig.cpp:78:99: error: no 'QVariant Kvantum::ThemeConfig::getValue(const QString&, const QString&, const QString&) const' member function declared in class 'Kvantum::ThemeConfig'
[  177s]  QVariant ThemeConfig::getValue(const QString& group, const QString& key, const QString &inherits) const
[  177s]                                                                                                    ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::frame_spec Kvantum::ThemeConfig::getFrameSpec(const QString&) const':
[  177s] themeconfig/ThemeConfig.cpp:118:48: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue(elementName, "inherits");
[  177s]                                                 ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::interior_spec Kvantum::ThemeConfig::getInteriorSpec(const QString&) const':
[  177s] themeconfig/ThemeConfig.cpp:155:48: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue(elementName, "inherits");
[  177s]                                                 ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::indicator_spec Kvantum::ThemeConfig::getIndicatorSpec(const QString&) const':
[  177s] themeconfig/ThemeConfig.cpp:182:48: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue(elementName, "inherits");
[  177s]                                                 ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::label_spec Kvantum::ThemeConfig::getLabelSpec(const QString&) const':
[  177s] themeconfig/ThemeConfig.cpp:202:48: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue(elementName, "inherits");
[  177s]                                                 ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::size_spec Kvantum::ThemeConfig::getSizeSpec(const QString&) const':
[  177s] themeconfig/ThemeConfig.cpp:265:48: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue(elementName, "inherits");
[  177s]                                                 ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::theme_spec Kvantum::ThemeConfig::getThemeSpec() const':
[  177s] themeconfig/ThemeConfig.cpp:285:50: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue("General","author", empty);
[  177s]                                                   ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::color_spec Kvantum::ThemeConfig::getColorSpec() const':
[  177s] themeconfig/ThemeConfig.cpp:474:55: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue("GeneralColors","window.color");
[  177s]                                                        ^
[  177s] themeconfig/ThemeConfig.cpp: In member function 'Kvantum::hacks_spec Kvantum::ThemeConfig::getHacksSpec() const':
[  177s] themeconfig/ThemeConfig.cpp:546:59: error: 'getValue' was not declared in this scope
[  177s]    QVariant v = getValue("Hacks","transparent_dolphin_view");
[  177s]                                                            ^
[  177s] Makefile:412: recipe for target 'ThemeConfig.o' failed
[  177s] make[1]: *** [ThemeConfig.o] Error 1
```

Any ideas? ;-)

**Comment by tsujan** [comment]
For some reason, the compiler doesn't find qvariant.h in your case. It belongs to qt5-base-5.5.0-1, according to https://www.archlinux.org/packages/extra/i686/qt5-base/files/ . Have you upgraded all Qt5 Arch packages to v5.5.0?

**Comment by mmetak** [comment]
Yes, 'qt5-base' is installed and all other Qt5 packages are updated.
Here's the full build log in OBS:
https://build.opensuse.org/build/home:metakcahura/Arch_Extra/i586/kvantum-git/_log

It happens in 'clean' build environment in OBS and on my local machine.

**Comment by tsujan** [comment]
I'm downloading Manjaro's KDE ISO to test under it on VirtualBox, hoping that its Qt5 is or can be easily upgraded to v5.5.0.

**Comment by tsujan** [comment]
After installing and upgrading the Manjaro system, Qt5 version became 5.5.0-1. I restarted the system (on VirtualBox), tried to compile Kvantum against Qt5-5.5.0-1, and got exactly the same error messages you mentioned. I'll investigate this problem later, when I have enough time. If you find the answer sooner, please tell me!

**Comment by tsujan** [comment]
Should be fixed now. The problem was that Qt5-5.5.0 is stricter than the previous versions. Please test the latest commit. And many thanks for reporting!

BTW, I can't help saying that I'm VERY impressed by Manjaro.

**Comment by mmetak** [comment]
It builds fine now. Thanks.
